services:
  api_gateway:
    build:  ./api-gateway
    ports:
      - "3500:3500"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3500
  users_microservice:
    build: ./users
    volumes:
      - ./users/src:/usr/src/app/src
    command: npm run start:dev
  payment_microservice:
    build: ./payment
    volumes:
      - ./payment/src:/usr/src/app/src
    command: npm run start:dev
  nats:
    image: nats
    ports:
      - 4222:4222
